"""add grievance tracking

Revision ID: 94392dcd8754
Revises: 66c1b4db192d
Create Date: 2026-10-09 16:52:32.914834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94392dcd8754'
down_revision: Union[str, Sequence[str], None] = '66c1b4db192d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grievances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('external_reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievances_application_id'), 'grievances', ['application_id'], unique=False)
    op.create_index(op.f('ix_grievances_id'), 'grievances', ['id'], unique=False)
    op.create_index(op.f('ix_grievances_user_id'), 'grievances', ['user_id'], unique=False)
    op.create_table('grievance_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grievance_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievance_status_history_grievance_id'), 'grievance_status_history', ['grievance_id'], unique=False)
    op.create_index(op.f('ix_grievance_status_history_id'), 'grievance_status_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grievance_status_history_id'), table_name='grievance_status_history')
    op.drop_index(op.f('ix_grievance_status_history_grievance_id'), table_name='grievance_status_history')
    op.drop_table('grievance_status_history')
    op.drop_index(op.f('ix_grievances_user_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_id'), table_name='grievances')
    op.drop_index(op.f('ix_grievances_application_id'), table_name='grievances')
    op.drop_table('grievances')
    # ### end Alembic commands ###
