"""add profile fields for eligibility rules

Revision ID: b8d11830c5ea
Revises: f0c48332f49c
Create Date: 2026-10-02 21:00:09.161583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d11830c5ea'
down_revision: Union[str, Sequence[str], None] = 'f0c48332f49c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_profiles', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('worker_profiles', sa.Column('monthly_income', sa.Double(), nullable=True))
    op.add_column('worker_profiles', sa.Column('epfo_status', sa.Boolean(), nullable=True))
    op.add_column('worker_profiles', sa.Column('esic_status', sa.Boolean(), nullable=True))
    op.add_column('worker_profiles', sa.Column('nps_status', sa.Boolean(), nullable=True))
    op.add_column('worker_profiles', sa.Column('income_tax_payer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_profiles', 'income_tax_payer')
    op.drop_column('worker_profiles', 'nps_status')
    op.drop_column('worker_profiles', 'esic_status')
    op.drop_column('worker_profiles', 'epfo_status')
    op.drop_column('worker_profiles', 'monthly_income')
    op.drop_column('worker_profiles', 'age')
    # ### end Alembic commands ###
